export const moduleData = {
  "Grade 1-3": [
    "M1 Sprite Lab",
    "M2 Advance Sprite Lab",
    "M3 Play Lab",
    "M4 Advance Play Lab",
    "M5 Minecraft",
    "M6 App Lab",
    "M7 Advance App Lab",
    "M8 Specialization in App Lab",
    "M9 Logic Building code.org",
    "M10 Game Lab",
    "M11 Game Development - I",
    "M12 Game Development - II",
    "M13 Scratch Basic",
    "M14 Scratch Intermediate",
    "M15 Scratch Advance",
    "M16 AI Basic",
    "M17 AI Advance",
    "M18 Thunkable Basic - I",
    "M19 Thunkable Basic - II",
    "M20 Thunkable Intermediate",
    "M21 Python",
    "M22 Advance Python",
    "M23 Basic Website Development",
    "M24 HTML CSS",
  ],

  "Grade 4-5": [
    "M1 Code.org (Sprite Lab, Play Lab and Minecraft)",
    "M2 App Lab - I",
    "M3 App Lab - II",
    "M4 Game Development - I",
    "M5 Game Development - II",
    "M6 Scratch Basic",
    "M7 Scratch Intermediate",
    "M8 Scratch Advance",
    "M9 Scratch Specialization",
    "M10 AI - I",
    "M11 AI - II",
    "M12 Thunkable Basic",
    "M13 Thunkable Intermediate - I",
    "M14 Thunkable Intermediate - II",
    "M15 Thunkable Advance",
    "M16 Web Development",
    "M17 Advance Web Development",
    "M18 Bootstrap 4",
    "M19 Specialization in Website Development",
    "M20 Capstone project on Website Development",
    "M21 Python Introduction",
    "M22 Advance Python",
    "M23 Specialization in Python",
    "M24 Development using JS",
  ],

  "Grade 6-8": [
    "M1 Scratch Intermediate",
    "M2 Scratch Advance",
    "M3 Scratch Specialization",
    "M4 Artificial Intelligence - I",
    "M5 Advance Artificial Intelligence",
    "M6 Thunkable Basic",
    "M7 Thunkable Intermediate - I",
    "M8 Thunkable Intermediate - II",
    "M9 Thunkable Advance",
    "M10 Fundamentals of HTML",
    "M11 Fundamentals of CSS",
    "M12 Bootstrap 4",
    "M13 Introduction to JavaScript",
    "M14 Brief of JavaScript",
    "M15 App Development using JS",
    "M16 Capstone project on Web Development",
    "M17 Python Basics",
    "M18 Let's Begin with Loops",
    "M19 Python Functions and Modules",
    "M20 Data Structures in Python",
    "M21 Object Oriented Programming",
    "M22 Game Building with Pygame",
    "M23 GUI using Python Tkinter",
    "M24 Welcome to Data Science",
  ],

  "Grade 9-12": [
    "M1 Fundamentals of HTML",
    "M2 Fundamental of CSS",
    "M3 Bootstrap 4",
    "M4 Introduction to JavaScript",
    "M5 Brief About JavaScript",
    "M6 Project on HTML, CSS, JS & Bootstrap",
    "M7 Python Introduction",
    "M8 Advanced Python",
    "M9 Specialization in Python",
    "M10 Data Structure - I",
    "M11 Data Structure - II",
    "M12 SQL using Python - I",
    "M13 SQL using Python - II",
    "M14 Welcome to Data Science",
    "M15 Visualization with Data Science - I",
    "M16 Statistics - I",
    "M17 Intro to Probability",
    "M18 Machine Learning - I",
    "M19 Machine Learning - II",
    "M20 Deep Learning - I",
    "M21 Deep Learning - II",
    "M22 Python Flask",
    "M23 Java Basics",
    "M24 Advanced Java",
  ],

  Roblox: [
    "Module 1",
    "Module 2",
    "Module 3",
    "Module 4",
    "Module 5",
    "Module 6",
  ],

  "AI expert (6-12)": [
    "Module 1",
    "Module 2",
    "Module 3",
    "Module 4",
    "Module 5",
    "Module 6",
    "Module 7",
    "Module 8",
  ],

  "AI genius (1-5)": [
    "Module 1",
    "Module 2",
    "Module 3",
    "Module 4",
    "Module 5",
    "Module 6",
    "Module 7",
    "Module 8",
  ],

  "Android Application Development Course": [
    "Module 1",
    "Module 2",
    "Module 3",
    "Module 4",
    "Module 5",
    "Module 6",
    "Module 7",
    "Module 8",
  ],

  "AP Computer Science A": [
    "Module 1",
    "Module 2",
    "Module 3",
    "Module 4",
    "Module 5",
    "Module 6",
    "Module 7",
    "Module 8",
  ],

  "Prompt Engineering for Kids": [
    "Module 1",
    "Module 2",
    "Module 3",
    "Module 4",
    "Module 5",
    "Module 6",
    "Module 7",
    "Module 8",
  ],

  "Block Coding Legend (Advance Level)": [
    "Module 1",
    "Module 2",
    "Module 3",
    "Module 4",
    "Module 5",
    "Module 6",
    "Module 7",
    "Module 8",
  ],
};
